stages:
  - pre-build
  - build
  - test
  - deploy

code-quality:
  stage: pre-build
  image: cirrusci/flutter:2.10.0
  tags: 
    - ci
  script:
    - flutter pub get
    - dart fix --apply
    - flutter pub run dart_code_metrics:metrics check-unused-files lib
    - flutter pub run dart_code_metrics:metrics analyze lib --reporter=html
  artifacts:
    paths:
      - metrics/
    expire_in: 1 week

build:
  stage: build
  image: cirrusci/flutter:2.10.0
  tags:
    - ci
  script:
    - flutter clean
    - flutter pub get
    - flutter pub run dart_code_metrics:metrics check-unused-files lib -d
    - flutter build apk --split-per-abi --release
  artifacts:
    paths:
      - build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
      - build/app/outputs/flutter-apk/app-x86_64-release.apk
    expire_in: 1 week
  only:
    - merge_requests